-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.sales) TOTAL_SALES 
FROM
    BOOK B
JOIN
    BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
JOIN
    AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE
    YEAR(BS.SALES_DATE) = 2022
    AND MONTH(BS.SALES_DATE) = 1
GROUP BY
    B.AUTHOR_ID,
    B.CATEGORY
ORDER BY
    B.AUTHOR_ID,
    B.CATEGORY DESC

    
