-- 코드를 작성해주세요
WITH FRONTEND AS (
    SELECT
        SKILLCODES.CODE
    FROM
        SKILLCODES
    WHERE
        CATEGORY = 'Front End'
) 
SELECT DISTINCT
    DEV.ID,
    DEV.EMAIL,
    DEV.FIRST_NAME,
    DEV.LAST_NAME
FROM
    FRONTEND FE
JOIN DEVELOPERS 
    DEV ON FE.CODE & DEV.SKILL_CODE > 0
ORDER BY
    DEV.ID
