SELECT 
    YEAR(ED.DIFFERENTIATION_DATE) YEAR,
    (MD.MAX_SIZE - ED.SIZE_OF_COLONY) YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) DIFF_YEAR,
        MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) MD
    ON YEAR(ED.DIFFERENTIATION_DATE) = MD.DIFF_YEAR
ORDER BY
    YEAR,
    YEAR_DEV;