-- 코드를 입력하세요
SELECT
    B.CATEGORY,
    SUM(S.SALES) TOTAL_SALES
FROM
    BOOK B
JOIN
    BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE
    YEAR(S.SALES_DATE) = 2022
    and MONTH(S.SALES_DATE) = 1
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY